### ISSUE TITLE
this 2 500s should be a 400

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/service-sequence-retrieval#18]
400, better UX
----------------

<img width="1241" alt="Screen Shot 2024-01-06 at 8 55 02 AM" src="https://github.com/VEuPathDB/service-sequence-retrieval/assets/16354313/4feae8b4-7acf-4149-890e-06d227bd315a">

==========================
==========================
==========================

500s  BAD UX
----------------

<img width="1056" alt="500UX" src="https://github.com/VEuPathDB/service-sequence-retrieval/assets/16354313/d64793c3-ab2a-417c-9a76-7f761684a869">

 **Query asks for data past end of contig**

<img width="1056" alt="500" src="https://github.com/VEuPathDB/service-sequence-retrieval/assets/16354313/b20c2097-4973-4371-86c3-e7d28a711fab">

**Malformed query; start point 101333 lies after end point 100833**

<img width="947" alt="Screen Shot 2023-11-29 at 4 57 46 PM" src="https://github.com/VEuPathDB/service-sequence-retrieval/assets/16354313/976de15e-1f2e-45a3-bf0e-daab0a5c80e6">

**Comment by dmgaldi** [comment]
To summarize, it looks like there are 3 issues at play:
1. User selects an end for the sequence that is before the start of the sequence. This causes a 500 instead of a 400. This is especially easy to do for a newbie if you don't know the length of the sequence and your selecting the beginning starting "downstream from the start" and the ending starting "upstream from the end".
<img width="442" alt="Screenshot 2024-02-16 at 4 25 10 PM" src="https://github.com/VEuPathDB/service-sequence-retrieval/assets/3497580/a1163200-b5ca-4a10-8868-2a78196706a3">

2. User selects an endpoint that is past the end of the contig. This also causes a 500 instead of a 400. This one is also easy to do if you don't know the length of the sequence:
<img width="390" alt="Screenshot 2024-02-16 at 4 28 06 PM" src="https://github.com/VEuPathDB/service-sequence-retrieval/assets/3497580/c7446567-08a4-4d06-9348-134bd77202a1">

_Note: the end of the sequence in the example is cut off, but is specified as 1000_

3. User requests more than the total allowed bases. This is correctly thrown as a 400, but there might be some work to map it properly in the ProcessQuery in WDK.

**Comment by dmgaldi** [comment]
[This other ticket](https://github.com/VEuPathDB/service-sequence-retrieval/issues/21) was created as a follow-up based on UX discussions that resulted from this ticket.
